on:
  push:
    branches:
      - master

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: windows-2019 
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3'
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect", "ggplot2"), type= 'binary')
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          rsconnect::setAccountInfo(name='${{ secrets.SHINYAPPS_USERNAME }}', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
          rsconnect::deployApp()
        shell: Rscript {0}
